src/cz/ucl/jsf/controller/TripConfigurationController.java
package cz.ucl.jsf.controller;

import java.io.Serializable;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

import javax.annotation.PostConstruct;
import javax.annotation.PreDestroy;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.persistence.EntityManager;
import javax.persistence.Query;

import cz.ucl.fa.model.Holiday;
import cz.ucl.fa.model.Transportation;
import cz.ucl.fa.model.util.JPAUtil;

@ManagedBean(name="holidayManager")
@ViewScoped
public class TripConfigurationController implements Serializable {
	private List<Holiday> allHolidays;
	private Holiday currentHoliday;
	private Transportation transportExample;

	private Long currentHolidayId;
	private Long transportId;
	
	@PostConstruct
	public void init() {
		System.out.println("!!! Holiday Controller initialized for VIEW SCOPE: " + this.toString());
	}
	
	@PreDestroy 
	public void destroy() {
		System.out.println("!!! Holiday Controller destroyed at the end of the VIEW SCOPE: " + this.toString());
	}


	/**
	 * Vrací seznam všech katalogových zájezdu z databáze
	 */
	@SuppressWarnings("unchecked")
	public List<Holiday> getAllHolidays() {
		EntityManager em = JPAUtil.createEntityManager();
		allHolidays = (List<Holiday>) em.createNamedQuery("Trip.getFixed")
				.getResultList();
		em.close();
		return allHolidays;
	}

	/**
	 * Nacítá objekt zájezdu z databáze na základě primárního klíče, uloženého ve vlastnosti currentHolidayId
	 */
	public Holiday getCurrentHoliday() {
		if (currentHoliday == null) {
			if (currentHolidayId != null) {
				EntityManager em = JPAUtil.createEntityManager();
				currentHoliday = em.find(Holiday.class, currentHolidayId);
				currentHoliday.getAccommodation().size();
				currentHoliday.getTransportation().size();
				currentHoliday.getServices().size();
				em.close();
			} else {
				currentHoliday = new Holiday();
			}
		}

		return currentHoliday;
	}

	/**
	 * Hodnota nastavena automaticky po stisku odkazu v tabulce všech zájezdu.
	 * Použito dále v getCurrentHoliday, saveHoliday, addTransport a removeTransport.
	 */
	public void setCurrentHolidayId(Long id) {
		currentHolidayId = id;
		currentHoliday = null;
	}
	

	public Long getCurrentHolidayId() {
		return currentHolidayId;
	}

	/**
	 * Objekt transportExample slouží jen pro nastavení hodnot, podle nichž má být vyhledáváno
	 * mezi všemi dopravními spojeními v databázi 
	 */
	public Transportation getTransportExample() {
		if (transportExample == null)
			transportExample = new Transportation();
		return transportExample;
	}

	/**
	 * Hodnota nastavena automaticky po stisku odkazu v tabulce všech nalezených dopravních spojení.
	 * Použito dále v addTransport.
	 */
	public void setTransportId(Long transportId) {
		this.transportId = transportId;
	}

	/**
	 * Seznam všech mest, ze kterých je možné nekam vyjet
	 */
	@SuppressWarnings("unchecked")
	public Map<String,String> getAllFromCities() {
		EntityManager em = JPAUtil.createEntityManager();
		List<String> result = (List<String>) em
				.createNamedQuery("Transportation.findAllFromLocations")
				.getResultList();
		em.close();
		return getStringMapFromList(result);
	}

	/**
	 * Seznam všech mest, do kterých je možno prijet
	 */
	@SuppressWarnings("unchecked")
	public Map<String,String> getAllToCities() {
		EntityManager em = JPAUtil.createEntityManager();
		List<String> result = (List<String>) em
				.createNamedQuery("Transportation.findAllToLocations")
				.getResultList();
		em.close();
		
		return getStringMapFromList(result);
	}
	
	private Map<String,String> getStringMapFromList(List<String> lst) {
		Map<String,String> resultMap = new HashMap<String,String>();
		for(String item : lst) {
			resultMap.put(item, item);
		}
		return resultMap;
	}

	/**
	 * Odebere dopravní spojení ze zájezdu
	 */
	public String removeTransport() {
		EntityManager em = JPAUtil.createEntityManager();
		Transportation selectedTransport = em.find(Transportation.class,
				this.transportId);

		em.getTransaction().begin();
		currentHoliday = em.merge(getCurrentHoliday());
		Set<Transportation> allTransports = getCurrentHoliday().getTransportation();
		allTransports.remove(selectedTransport);
		em.getTransaction().commit();
		em.close();

		return "transport_removed";
	}
	
	/**
	 * Ukládá aktuální hodnotu objektu currentHoliday do databáze
	 */
	public String saveHoliday() {
		EntityManager em = JPAUtil.createEntityManager();
		em.getTransaction().begin();
		currentHoliday = em.merge(getCurrentHoliday());
		em.getTransaction().commit();
		em.close();
		
		return "holiday_saved";
	}

	/**
	 * Pridává do zájezdu nové dopravní spojení
	 */
	public String addTransport() {
		EntityManager em = JPAUtil.createEntityManager();
		Transportation selectedTransport = em.find(Transportation.class,
				this.transportId);

		em.getTransaction().begin();
		currentHoliday = em.merge(getCurrentHoliday());
		getCurrentHoliday().addTransportation(selectedTransport);
		em.getTransaction().commit();
		em.close();

		return "transport_added";
	}

	/**
	 * Vyhledává dopravní spojení v databázi na základe podmínek, uložených v objektu transportExample 
	 */	
	public List<Transportation> getFoundTransports() {
		String qString = "SELECT t FROM Transportation t WHERE t.from = :transFrom AND t.to = :transTo ";
		if (transportExample.getDeparture() != null)
			qString += " AND t.departure > :dep_from AND t.departure < :dep_to ";

		EntityManager em = JPAUtil.createEntityManager();
		Query q = em.createQuery(qString);
		q.setParameter("transFrom", transportExample.getFrom());
		q.setParameter("transTo", transportExample.getTo());
		if (transportExample.getDeparture() != null) {
			Calendar cal = Calendar.getInstance();
			cal.setTime(transportExample.getDeparture());

			cal.set(Calendar.HOUR_OF_DAY, 0);
			cal.set(Calendar.MINUTE, 0);
			cal.set(Calendar.SECOND, 0);

			Date day1 = new Date(cal.getTimeInMillis());
			q.setParameter("dep_from", day1);

			cal.set(Calendar.DAY_OF_MONTH, cal.get(Calendar.DAY_OF_MONTH) + 1);
			Date day2 = new Date(cal.getTimeInMillis());
			q.setParameter("dep_to", day2);
		}

		List<Transportation> result = (List<Transportation>) q.getResultList();
		em.close();
		return result;
	}
}

WebContent/view/buy_trip.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:a4j="http://richfaces.org/a4j"
	xmlns:rich="http://richfaces.org/rich"
	xmlns:ucl="http://www.unicorcollege.cz/JEE/Library">
<body>
<ui:composition template="/template/blue_travel.xhtml">
	<ui:define name="pageTitle">#{local.buyTrip}</ui:define>
	<ui:define name="primaryContent">
		<h:outputLabel value="Hello, start"/>

		<h:form>
			<h:commandButton value="Place order" action="order" />
		</h:form>


		DOPLNIT

	</ui:define>
</ui:composition>
</body>
</html>

WebContent/view/client.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:a4j="http://richfaces.org/a4j"
	xmlns:rich="http://richfaces.org/rich"
	xmlns:ucl="http://www.unicorcollege.cz/JEE/Library">
<body>
<ui:composition template="/template/blue_travel.xhtml">
	<ui:define name="pageTitle">#{local.customerDetail}</ui:define>
	<ui:define name="metadata">
		<f:metadata>
			<f:viewParam name="clientId" value="#{customerController.selectedCustomerId}" required="true"/>
		</f:metadata>
	</ui:define>
	<ui:define name="primaryContent">
		
		<h3>#{local.detailsFor} #{customerController.currentCustomer.name}</h3>
		<rich:panel>
		  <f:facet name="header">#{local.trips}</f:facet>
		  <rich:dataGrid value="#{customerController.currentCustomer.contracts}" var="contract">
		  	<rich:panel rendered="#{contract ne null}">
		  		<ucl:trip value="#{contract.holiday}" />
		  	</rich:panel>
		  </rich:dataGrid>
        </rich:panel>        
	</ui:define>
</ui:composition>
</body>
</html>

WebContent/view/client_list.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:a4j="http://richfaces.org/a4j"
	xmlns:rich="http://richfaces.org/rich"
	xmlns:ucl="http://www.unicorcollege.cz/JEE/Library">
<h:body>
<ui:composition template="/template/blue_travel.xhtml">
	<ui:define name="pageTitle">#{local.clientList}</ui:define>	
	<ui:define name="primaryContent">
		<h:form>
			<h:panelGrid columns="3">
				<h:outputText value="#{local.surname}: " />
				<h:inputText value="#{customerController.searchSurname}" />
				<h:commandButton value="#{local.search}" action="#{customerController.searchCustomers}" >
					<a4j:ajax execute="@form" render="customers"/>
				</h:commandButton>
			</h:panelGrid>
				
			<br/>
			<hr/>
			<br/>
			<br/>

				<rich:dataTable id="customers" var="customer"
					value="#{customerController.customersFound}">
					<rich:column>
						<f:facet name="header">#{local.firstName}</f:facet>
        				#{customer.firstName}
        			</rich:column>
					<rich:column>
						<f:facet name="header">#{local.surname}</f:facet>
        				#{customer.surname}        	
					</rich:column>
					<rich:column>
						<h:link value="#{local.select}" outcome="show_detail" includeViewParams="true">
							<f:param name="clientId" value="#{customer.id}"/>
						</h:link>
					</rich:column>
				</rich:dataTable>						
		</h:form>
	</ui:define>
</ui:composition>
</h:body>
</html>

WebContent/view/trip.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:a4j="http://richfaces.org/a4j"
	xmlns:rich="http://richfaces.org/rich"	>
<body>
<ui:composition template="/template/blue_travel.xhtml">
	<ui:define name="pageTitle">#{local.tripDetail}</ui:define>
	<ui:define name="metadata">
		<f:metadata>
			<f:viewParam name="tripId" value="#{holidayManager.currentHolidayId}" />
		</f:metadata>
	</ui:define>
	<ui:define name="primaryContent">
		<h:form>  
		  <rich:collapsiblePanel header="#{local.details}">			
			  <h:panelGrid columns="3">
				<h:outputText value="#{local.name}: " />
				<h:inputText id="holidayName" value="#{holidayManager.currentHoliday.name}" />
				<rich:message for="holidayName" />
				
				<h:outputText value="#{local.starts}: " />
				<rich:calendar id="holidayStarts"  datePattern="dd.M.yyyy" value="#{holidayManager.currentHoliday.starts}" />
				<rich:message for="holidayStarts" />
				
				<h:outputText value="#{local.ends}: " />
				<rich:calendar id="holidayEnds" datePattern="dd.M.yyyy" value="#{holidayManager.currentHoliday.ends}" />
				<rich:message for="holidayEnds" />				
				
				<h:outputText value="#{local.price}: " />
				<h:inputText id="holidayPrice" value="#{holidayManager.currentHoliday.price}" />
				<rich:message for="holidayPrice" />
			  </h:panelGrid>
			  <h:commandButton value="#{local.save}" action="#{holidayManager.saveHoliday}" >
			  	<f:ajax execute="@form" render="@form"/>
			  </h:commandButton>			
		  </rich:collapsiblePanel>
		</h:form>
		<rich:panel>
		  <f:facet name="header">#{local.transportation}</f:facet>
		  <h3>#{local.existingTransportation}</h3>
		  <h:form>		
            <rich:dataTable id="transportTable" var="transport" value="#{ucl:asList(holidayManager.currentHoliday.transportation)}">
        	  <rich:column>
        		  <f:facet name="header">#{local.type}</f:facet>
        		  #{transport.type}
        	  </rich:column>
        	  <rich:column>
        		  <f:facet name="header">#{local.dateLeaving}</f:facet>
        		  <h:outputText value="#{transport.departure}">
        			  <f:convertDateTime type="date" />
        		  </h:outputText>
        	  </rich:column>
        	  <rich:column>
        		  <f:facet name="header">#{local.timeLeaving}</f:facet>
        		  <h:outputText value="#{transport.departure}">
        			  <f:convertDateTime type="time" />
          	  	  </h:outputText>
        	  </rich:column>
        	  <rich:column>
        		  <f:facet name="header">#{local.fromLocation}</f:facet>
        		  #{transport.from}
        	  </rich:column>
        	  <rich:column>
        		  <f:facet name="header">#{local.toLocation}</f:facet>
        		  #{transport.to}
        	  </rich:column>
        	  <rich:column>
        		  <f:facet name="header">#{local.duration}</f:facet>
        		  <h:outputText value="#{(transport.arrival.time - transport.departure.time)/3600000}">
        			  <f:convertNumber maxFractionDigits="1"/>
        		  </h:outputText>      			
        	  </rich:column>
        	  <rich:column>
        		<h:commandLink value="#{local.remove}" action="#{holidayManager.removeTransport}">
        		    <a4j:ajax render="transportTable" />
        			<f:setPropertyActionListener target="#{holidayManager.transportId}" value="#{transport.id}"/>
        		</h:commandLink>
        	  </rich:column>
            </rich:dataTable>          
          </h:form>
          <h3>#{local.findAddTransportation}</h3>
          <h:form>
          	<h:panelGrid columns="2">
          		<h:outputText value="#{local.cityFrom}:" />
          		<h:selectOneMenu value="#{holidayManager.transportExample.from}">
          			<f:selectItems value="#{holidayManager.allFromCities}" />          			
          		</h:selectOneMenu>
          		
          		<h:outputText value="#{local.cityTo}:" />
          		<h:selectOneMenu value="#{holidayManager.transportExample.to}">
          			<f:selectItems value="#{holidayManager.allToCities}" />
          		</h:selectOneMenu>
          		
          		<h:outputText value="#{local.departureDate}:" />
          		<rich:calendar datePattern="dd.M.yyyy" value="#{holidayManager.transportExample.departure}"/>
          	</h:panelGrid>
          	<h:commandLink value="#{local.findTransports}">
          	  <a4j:ajax execute="@form" render="foundTransports" />
          	</h:commandLink>
          </h:form>
          <h3>#{local.foundTransportation}</h3>
          <h:form>
            <rich:dataTable id="foundTransports" var="transport" value="#{holidayManager.foundTransports}">
       		  <rich:column>
        		  <f:facet name="header">#{local.type}</f:facet>
        		  #{transport.type}
        	  </rich:column>
        	  <rich:column>
        		  <f:facet name="header">#{local.dateLeaving}</f:facet>
        		  <h:outputText value="#{transport.departure}">
        			  <f:convertDateTime type="date" />
        		  </h:outputText>
        	  </rich:column>
        	  <rich:column>
        		  <f:facet name="header">#{local.timeLeaving}</f:facet>
        		  <h:outputText value="#{transport.departure}">
        			  <f:convertDateTime type="time" />
        		  </h:outputText>
        	  </rich:column>
        	  <rich:column>
        	  	<a4j:commandLink value="#{local.addTransportation}" action="#{holidayManager.addTransport}" render="transportTable">
        	  		<f:setPropertyActionListener target="#{holidayManager.transportId}" value="#{transport.id}"/>
        	  	</a4j:commandLink>
        	  </rich:column>
            </rich:dataTable>
          </h:form>
        </rich:panel>
        
        <rich:panel>
          <f:facet name="header">#{local.accommodation}</f:facet>
        </rich:panel>
	</ui:define>
</ui:composition>
</body>
</html>

WebContent/view/trip_list.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:rich="http://richfaces.org/rich">
<body>
<ui:composition template="/template/blue_travel.xhtml">
	<ui:define name="pageTitle">#{local.tripList}</ui:define>
	<ui:define name="primaryContent">
		<h:form>
        <rich:dataTable var="trip" value="#{holidayManager.allHolidays}">
        	<rich:column>
        		<f:facet name="header">#{local.name}</f:facet>
        		#{trip.name}
        	</rich:column>
        	<rich:column>
        		<f:facet name="header">#{local.starts}</f:facet>
        		#{trip.starts}
        	</rich:column>
        	<rich:column>
        		<f:facet name="header">#{local.ends}</f:facet>
        		#{trip.ends}
        	</rich:column>
        	<rich:column>
        		<f:facet name="header">#{local.price}</f:facet>
        		#{trip.price}
        	</rich:column>
        	<rich:column>
        		<h:link value="#{local.tripDetail}" outcome="show_detail" includeViewParams="true">
        			<f:param name="tripId" value="#{trip.id}" />
        		</h:link>        		
        	</rich:column>
        </rich:dataTable>
        </h:form>
	</ui:define>
</ui:composition>
</body>
</html>