src/cz/ucl/flow/order/OrderBean.java
package cz.ucl.flow.order;

/**
 * Created by hideo on 12.04.16.
 */
import cz.ucl.fa.model.Customer;
import cz.ucl.fa.model.Holiday;
import cz.ucl.fa.model.Traveller;
import cz.ucl.fa.model.util.JPAUtil;
import cz.ucl.jsf.controller.PurchaseController;

import javax.annotation.PostConstruct;
import javax.annotation.PreDestroy;
import javax.faces.event.ValueChangeEvent;
import javax.faces.flow.FlowScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.EntityManager;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

@Named
@FlowScoped("order")
public class OrderBean implements Serializable {

    @PostConstruct
    public void init() {
        System.out.println("!!! Entered Order flow " + this.toString());
    }

    @PreDestroy
    public void destroy() {
        System.out.print("!!! Leaving Order flow " + this.toString());
    }

    @Inject
    private PurchaseController purchaseController;

    public long getSelectedTripId() {
        return selectedTripId;
    }

    public void setSelectedTripId(long selectedTripId) {
        this.selectedTripId = selectedTripId;
    }

    private long selectedTripId = -1;

    public Customer getCustomer() {
        return customer;
    }

    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    private Customer customer;

    private Holiday selectedHoliday;

    public Holiday getSelectedHoliday() {
        setSelectedHoliday(selectedTripId);
        System.out.println("holiday je " + this.selectedHoliday + "id" + selectedTripId);
        return selectedHoliday;
    }
    public void setSelectedHoliday(long selectedTripId) {
        System.out.println("selectedTripId je " + selectedTripId);
        if (selectedTripId != -1) {
            EntityManager em = JPAUtil.createEntityManager();
            selectedHoliday = em.find(Holiday.class, selectedTripId);
            selectedHoliday.getAccommodation().size();
            selectedHoliday.getTransportation().size();
            selectedHoliday.getServices().size();
            em.close();
        }
    }

    public void tripChanged(ValueChangeEvent e) {
        if (null != e.getNewValue() ) {
            selectedTripId = ((Number) e.getNewValue()).longValue();
            System.out.println("\ttripChanged fired with " + selectedTripId);
        }
    }

    private String firstName;
    private String surname;
    private String ccNumber;
    private String ccValidity;
    private String travellerIdNumber;
    private String travellerFirstName;
    private String travellerSurname;
    private List<Traveller> travellers = new ArrayList<>();
    private Traveller traveller;

    public List<Traveller> getTravellers() {
        return travellers;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
        travellerFirstName = firstName;
    }

    public String getSurname() {
        return surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
        travellerSurname = surname;
    }

    public String removeTraveller(Traveller traveller) {
        travellers.remove(traveller);
        return null;
    }


    public String getCcValidity() {
        return ccValidity;
    }

    public void setCcValidity(String ccValidity) {
        this.ccValidity = ccValidity;
    }

    public String getCcNumber() {
        return ccNumber;
    }

    public void setCcNumber(String ccNumber) {
        this.ccNumber = ccNumber;
    }


    public String getTravellerFirstName() {
        return travellerFirstName;
    }

    public void setTravellerFirstName(String travellerFirstName) {
        this.travellerFirstName = travellerFirstName;
    }

    public String getTravellerSurname() {
        return travellerSurname;
    }

    public void setTravellerSurname(String travellerSurname) {
        this.travellerSurname = travellerSurname;
    }

    public String getTravellerIdNumber() {
        return travellerIdNumber;
    }

    public void setTravellerIdNumber(String travellerIdNumber) {
        this.travellerIdNumber = travellerIdNumber;
    }


    public void addTraveller() {
        Traveller traveller = new Traveller();
        traveller.setFirstName(travellerFirstName);
        traveller.setSurname(travellerSurname);
        traveller.setIdNumber(travellerIdNumber);
        travellers.add(traveller);
        travellerIdNumber="";
        travellerFirstName="";
        travellerSurname="";
    }



    public String getReturnValue() {
        return "/index.jsf";
    }

}

src/cz/ucl/jsf/controller/PurchaseController.java
package cz.ucl.jsf.controller;

import java.io.Serializable;
import java.util.*;

import javax.annotation.PostConstruct;
import javax.annotation.PreDestroy;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.context.FacesContext;
import javax.faces.event.ValueChangeEvent;
import javax.faces.flow.FlowScoped;
import javax.inject.Named;
import javax.persistence.EntityManager;
import javax.validation.constraints.Pattern;

import com.sun.istack.internal.NotNull;
import cz.ucl.fa.model.Contract;
import cz.ucl.fa.model.CreditCard;
import cz.ucl.fa.model.Customer;
import cz.ucl.fa.model.Holiday;
import cz.ucl.fa.model.Traveller;
import cz.ucl.fa.model.util.JPAUtil;
import org.hibernate.Criteria;
import org.hibernate.Session;
import org.hibernate.criterion.Restrictions;

@ManagedBean(name = "purchaseController")
@Named
@FlowScoped("order")
public class PurchaseController implements Serializable {
    /**
     * Vznikající objekt smlouvy
     */
    private Contract contract = new Contract();

    /**
     * Pomocné objekty pro přidávání cestujících do smlouvy
     */
    private Traveller currentTraveller = new Traveller();
    private Integer selectedTravellerPos;
    private List<Traveller> travellers = new ArrayList<>();

    /**
     * Proměnné pro práci s existujícími zákazníky
     */
    private boolean existingCustomer;
    private Long existingCustomerId;

    /**
     * Asociativní pole Název->ID všech zájezdů
     */
    private Map<String, Long> allTrips;

    /**
     * Pomocná pole pro ukládání čísla a platnosti kreditní karty
     */
    private String[] creditCardNo = new String[4];
    private String[] creditCardValidity = new String[2];

    /**
     * Vyhledá všechny katalogové zájezdy a naplní je do asociativního pole
     * allTrips (v podobě vhodné k použití pro f:selectItems)
     */
    @SuppressWarnings("unchecked")
    public Map<String, Long> getAllTrips() {
        if (allTrips == null) {
            allTrips = new TreeMap<String, Long>();
            allTrips.put("", -1L);

            EntityManager em = JPAUtil.createEntityManager();
            List<Object[]> queryResult = em.createNamedQuery(
                    "Trip.getAllNamesAndIds").getResultList();
            for (Object[] item : queryResult) {
                allTrips.put((String) item[0], (Long) item[1]);
            }
        }
        return allTrips;
    }

    private Holiday selectedHoliday;

    public Holiday getSelectedHoliday() {
        return selectedHoliday;
    }

    private long selectedTripId = -1;

    public long getSelectedTripId() {
        return selectedTripId;
    }

    /**
     * Na základě nastavení identifikátoru zájezdu (bude voláno JSF implementací poté,
     * co uživatel vybere ze seznamu) z databáze načte objekt typu Holiday a naplní do
     * vznikajícího objektu smlouvy (contract)
     */
    public void setSelectedTripId(long selectedTripId) {
        if (selectedTripId != -1) {
            this.selectedTripId = selectedTripId;
            EntityManager em = JPAUtil.createEntityManager();
            selectedHoliday = em.find(Holiday.class, selectedTripId);
            selectedHoliday.getAccommodation().size();
            selectedHoliday.getTransportation().size();
            selectedHoliday.getServices().size();
            contract.setHoliday(selectedHoliday);
            em.close();
        }
    }

    public void tripChanged(ValueChangeEvent e) {
        if (null != e.getNewValue()) {
            setSelectedTripId(((Number) e.getNewValue()).longValue());
        }
    }


    private Customer currentCustomer = new Customer();

    public String getCurrentCustomerFirstName() {
        return currentCustomer.getFirstName();
    }

    public void setCurrentCustomerFirstName(String firstName) {
        currentCustomer.setFirstName(firstName);
        currentTraveller.setFirstName(firstName);
    }

    public String getCurrentCustomerSurname() {
        return currentCustomer.getSurname();
    }

    @SuppressWarnings("unchecked")
    public void setCurrentCustomerSurname(String surname) {
        currentCustomer.setSurname(surname);
        currentTraveller.setSurname(surname);
        if (knownCustomer(currentCustomer)) {
            existingCustomer = true;
            EntityManager em = JPAUtil.createEntityManager();
            Session session = em.unwrap(Session.class);
            Criteria cr = session.createCriteria(Customer.class);
            List<Customer> results = cr.list();
            em.close();
            existingCustomerId = results.get(0).getId();
        } else {
            existingCustomerId = null;
            existingCustomer = false;
        }
        contract.setCustomer(currentCustomer);
    }

    @SuppressWarnings("unchecked")
    private boolean knownCustomer(Customer customer) {
        EntityManager em = JPAUtil.createEntityManager();
        Session session = em.unwrap(Session.class);
        Criteria cr = session.createCriteria(Customer.class);
        cr.add(Restrictions.eq("firstName",customer.getFirstName()));
        cr.add(Restrictions.eq("surname",customer.getSurname()));
        List<Customer> results = cr.list();
        em.close();
        return !results.isEmpty();
    }


    @Pattern(regexp = "(\\d{4}([- ])?){3}\\d{4}", message = "16 numbers")
    @NotNull
    private String ccNumber;

    public String getCcNumber() {
        return ccNumber;
    }

    /**
     * Sets ccNumber[] according to provided parameter.
     *
     * @param ccNumber is expected to be in form
     *                 xxxx-xxxx-xxxx-xxxx or
     *                 xxxx xxxx xxxx xxxx or
     *                 xxxxxxxxxxxxxxxx
     */
    public void setCcNumber(String ccNumber) {
        String number = ccNumber.replace("- ", "");
        StringBuilder s = new StringBuilder(number).insert(4, "-").insert(9, "-").insert(14, "-");
        creditCardNo = s.toString().split("-");
        this.ccNumber = ccNumber;
    }

    @Pattern(regexp = "\\d{2}(/)?\\d{2}", message = "mm/yy")
    @NotNull
    private String ccValidity;

    public String getCcValidity() {
        return ccValidity;
    }

    /**
     * Sets ccValidity[] according to provided parameter.
     *
     * @param ccValidity is expected to be in form of <tt>mm/yy</tt> or <tt>mmyy<tt/>.
     */
    public void setCcValidity(String ccValidity) {
        String number = ccValidity.replace("/", "");
        StringBuilder s = new StringBuilder(number).insert(2, "/");
        creditCardValidity = s.toString().split("/");
        this.ccValidity = ccValidity;
    }


    /**
     * Pro existujícího zákazníka zkopíruje jméno/příjmení z databáze pro nastavení
     * hodnot do objektu currentTraveller.
     */
    public void copyTravellerFromCustomer() {
        currentTraveller = new Traveller();
        if (existingCustomer && existingCustomerId != null) {
            EntityManager em = JPAUtil.createEntityManager();
            Customer existingCustomerValue = (Customer) em.find(Customer.class,
                    existingCustomerId);
            currentTraveller.setSurname(existingCustomerValue.getSurname());
            currentTraveller.setFirstName(existingCustomerValue.getFirstName());
            em.close();
        } else {
            currentTraveller.setSurname(contract.getCustomer().getSurname());
            currentTraveller
                    .setFirstName(contract.getCustomer().getFirstName());
        }

    }

    @SuppressWarnings("unchecked")
    private Traveller knownTraveller(String id) {
        EntityManager em = JPAUtil.createEntityManager();
        Session session = em.unwrap(Session.class);
        Criteria cr = session.createCriteria(Traveller.class);
        cr.add(Restrictions.eq("idNumber",id));
        List<Traveller> results = cr.list();
        em.close();
        if (results.isEmpty()) return currentTraveller;
        else return results.get(0);
    }

    public String getTravellerIdNumber() {
        return currentTraveller.getIdNumber();
    }

    public void setTravellerIdNumber(String idNumber) {
        currentTraveller = knownTraveller(idNumber);
        currentTraveller.setIdNumber(idNumber);
    }

    public String getTravellerFirstName() {
        return currentTraveller.getFirstName();
    }

    public void setTravellerFirstName(String firstName) {
        currentTraveller.setFirstName(firstName);
    }

    public String getTravellerSurname() {
        return currentTraveller.getSurname();
    }

    public void setTravellerSurname(String surname) {
        currentTraveller.setSurname(surname);
    }

    public void addTraveller() {
        travellers.add(currentTraveller);
        currentTraveller = new Traveller();
    }

    public void removeTraveller(Traveller t) {
        travellers.remove(t);
    }

    public List<Traveller> getTravellers() {
        return travellers;
    }

    /**
     * Provede potvrzení smlouvy a její zápis do databáze. Rozlišuje mezi existujícím
     * a novým zákazníkem. Neobsahuje (zatím) validace
     */
    public String confirmContract() {
        EntityManager em = JPAUtil.createEntityManager();
        if (existingCustomer) {
            if (existingCustomerId == null) {
                FacesContext.getCurrentInstance().addMessage(
                        null,
                        new FacesMessage("No customer selected",
                                "No existing customer was selected"));
                return "validationError";
            } else {
                contract.setCustomer((Customer) em.find(Customer.class,
                        existingCustomerId));
            }

WebContent/order/order-client_details.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
<f:view>
    <ui:composition template="/template/blue_travel.xhtml">
        <ui:define name="pageTitle">Customer details</ui:define>
        <ui:define name="primaryContent">
            <h:form>
                <h:outputLabel for="firstName" value="First name: "/>
                <h:inputText id="firstName" value="#{purchaseController.currentCustomerFirstName}" required="true" requiredMessage="Missing name."/>
                <h:message for="firstName"/>
                <br/>
                <h:outputLabel for="surname" value="Surname: "/>
                <h:inputText id="surname" value="#{purchaseController.currentCustomerSurname}" required="true" requiredMessage="Missing surname."/>
                <h:message for="surname"/>
                <br/>
                <h:panelGroup layout="block">
                <h:outputLabel for="ccNumber" value="Credit card: "/>
                    <h:inputText id="ccNumber" value="#{purchaseController.ccNumber}"/>
                <h:message for="ccNumber"/>
                </h:panelGroup>
                <br/>
                <h:outputLabel for="ccValidThru" value="Valid untill: "/>
                <h:inputText id="ccValidThru" value="#{purchaseController.ccValidity}"/>
                <h:message for="ccValidThru"/>
                <br/>

                <h:commandButton value="Proceed" action="order-travellers"/>
            </h:form>
        </ui:define>
    </ui:composition>
</f:view>
</html>

WebContent/order/order-confirm.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:rich="http://richfaces.org/rich"
      xmlns:ucl="http://www.unicorcollege.cz/JEE/Library">
<f:view>
    <ui:composition template="/template/blue_travel.xhtml">
        <ui:define name="pageTitle">Order confirmation</ui:define>
        <ui:define name="primaryContent">
            <h:form>
                <h:panelGrid columns="2">
                    <ucl:trip value="#{purchaseController.selectedHoliday}"/>
                    <rich:dataTable id="travellers" var="traveller"
                                    value="#{purchaseController.travellers}">
                        <rich:column>
                            <f:facet name="header">#{local.firstName}</f:facet>
                            #{traveller.firstName}
                        </rich:column>
                        <rich:column>
                            <f:facet name="header">#{local.surname}</f:facet>
                            #{traveller.surname}
                        </rich:column>
                        <rich:column>
                            <f:facet name="header">Id</f:facet>
                            #{traveller.idNumber}
                        </rich:column>
                        <rich:column>
                            <h:commandLink value="#{local.remove}" action="#{purchaseController.removeTraveller(traveller)}"/>
                        </rich:column>
                    </rich:dataTable>
                </h:panelGrid>
                <h:commandButton value="Confirm" action="#{purchaseController.confirmContract}"/>
                <h:commandButton value="Exit" action="returnFromOrderFlow"/>
            </h:form>
        </ui:define>
    </ui:composition>
</f:view>
</html>

WebContent/order/order-travellers.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:rich="http://richfaces.org/rich"
      xmlns:a4j="http://richfaces.org/a4j">
<f:view>

<ui:composition template="/template/blue_travel.xhtml">
        <ui:define name="pageTitle">Add Travellers</ui:define>
        <ui:define name="primaryContent">
            <h:form>
                <h:messages/>
                <h:panelGrid columns="2">
                    <h:panelGroup layout="block">
                        <h:outputLabel for="idNumber" value="ID: "/>
                        <h:inputText id="idNumber" value="#{purchaseController.travellerIdNumber}">
                            <a4j:ajax event="blur" render="firstName surname" execute="@this"/>
                        </h:inputText>
                        <br/>
                        <h:outputLabel for="firstName" value="First name: "/>
                        <h:inputText id="firstName" value="#{purchaseController.travellerFirstName}"/>
                        <br/>
                        <h:outputLabel for="surname" value="Surname: "/>
                        <h:inputText id="surname" value="#{purchaseController.travellerSurname}"/>
                    </h:panelGroup>


                    <rich:dataTable id="travellers" var="traveller"
                                    value="#{purchaseController.travellers}">
                        <rich:column>
                            <f:facet name="header">#{local.firstName}</f:facet>
                            #{traveller.firstName}
                        </rich:column>
                        <rich:column>
                            <f:facet name="header">#{local.surname}</f:facet>
                            #{traveller.surname}
                        </rich:column>
                        <rich:column>
                            <f:facet name="header">Id</f:facet>
                            #{traveller.idNumber}
                        </rich:column>
                        <rich:column>
                            <h:commandLink value="#{local.remove}" action="#{purchaseController.removeTraveller(traveller)}"/>
                        </rich:column>
                    </rich:dataTable>
                </h:panelGrid>


                <br/>
                <h:commandButton value="Add" action="#{purchaseController.addTraveller}"/>
                <h:commandButton value="Proceed" action="order-confirm"/>
            </h:form>
        </ui:define>
    </ui:composition>
</f:view>
</html>

WebContent/order/order.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ucl="http://www.unicorcollege.cz/JEE/Library">
<f:view>
    <ui:composition template="/template/blue_travel.xhtml">
        <ui:define name="pageTitle">Trip selection</ui:define>
        <ui:define name="primaryContent">
            <h:form>
                <h:panelGrid columns="3" rowClasses="">
                    <h:selectOneListbox id="trip" value="#{purchaseController.selectedTripId}"
                                        onchange="submit()"
                                        valueChangeListener="#{purchaseController.tripChanged}">
                        <f:selectItems value="#{purchaseController.allTrips}"/>
                        <f:ajax event="click" execute="@this" render="tripDetails"/>
                    </h:selectOneListbox>

                    <h:panelGroup id="tripDetails"
                                  rendered="#{purchaseController.selectedTripId ne -1}">
                        <ucl:trip value="#{purchaseController.selectedHoliday}"/>
                    </h:panelGroup>
                    <h:commandButton value="Proceed" action="order-client_details"
                                     rendered="#{purchaseController.selectedTripId ne -1}"/>
                </h:panelGrid>

            </h:form>
        </ui:define>
    </ui:composition>
</f:view>
</html>